/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lodgea-csharp.Client.OpenAPIDateConverter;

namespace lodgea-csharp.com.lodgea.model
{
    /// <summary>
    /// PropertiesPropertyIdGet200Response
    /// </summary>
    [DataContract]
    public partial class PropertiesPropertyIdGet200Response :  IEquatable<PropertiesPropertyIdGet200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesPropertyIdGet200Response" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PropertiesPropertyIdGet200Response() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesPropertyIdGet200Response" /> class.
        /// </summary>
        /// <param name="property">property (required).</param>
        /// <param name="productList">productList (required).</param>
        public PropertiesPropertyIdGet200Response(PropertiesPropertyIdGet200ResponseProperty property = default(PropertiesPropertyIdGet200ResponseProperty), List<PropertiesPropertyIdGet200ResponseProductListInner> productList = default(List<PropertiesPropertyIdGet200ResponseProductListInner>))
        {
            // to ensure "property" is required (not null)
            if (property == null)
            {
                throw new InvalidDataException("property is a required property for PropertiesPropertyIdGet200Response and cannot be null");
            }
            else
            {
                this.Property = property;
            }

            // to ensure "productList" is required (not null)
            if (productList == null)
            {
                throw new InvalidDataException("productList is a required property for PropertiesPropertyIdGet200Response and cannot be null");
            }
            else
            {
                this.ProductList = productList;
            }

        }

        /// <summary>
        /// Gets or Sets Property
        /// </summary>
        [DataMember(Name="property", EmitDefaultValue=true)]
        public PropertiesPropertyIdGet200ResponseProperty Property { get; set; }

        /// <summary>
        /// Gets or Sets ProductList
        /// </summary>
        [DataMember(Name="productList", EmitDefaultValue=true)]
        public List<PropertiesPropertyIdGet200ResponseProductListInner> ProductList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PropertiesPropertyIdGet200Response {\n");
            sb.Append("  Property: ").Append(Property).Append("\n");
            sb.Append("  ProductList: ").Append(ProductList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PropertiesPropertyIdGet200Response);
        }

        /// <summary>
        /// Returns true if PropertiesPropertyIdGet200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of PropertiesPropertyIdGet200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PropertiesPropertyIdGet200Response input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Property == input.Property ||
                    (this.Property != null &&
                    this.Property.Equals(input.Property))
                ) && 
                (
                    this.ProductList == input.ProductList ||
                    this.ProductList != null &&
                    input.ProductList != null &&
                    this.ProductList.SequenceEqual(input.ProductList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Property != null)
                    hashCode = hashCode * 59 + this.Property.GetHashCode();
                if (this.ProductList != null)
                    hashCode = hashCode * 59 + this.ProductList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
