/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lodgea-csharp.Client.OpenAPIDateConverter;

namespace lodgea-csharp.com.lodgea.model
{
    /// <summary>
    /// PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner
    /// </summary>
    [DataContract]
    public partial class PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner :  IEquatable<PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner" /> class.
        /// </summary>
        /// <param name="addressLine">The first line of the address for this contact (required).</param>
        /// <param name="propertyName">The name of the property for this contact.</param>
        /// <param name="cityName">The city of this contact (required).</param>
        /// <param name="postalCode">The postal code of this contact (required).</param>
        /// <param name="state">The state/region of this contact.</param>
        /// <param name="countryCode">The country code of this contact.</param>
        public PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner(string addressLine = default(string), string propertyName = default(string), string cityName = default(string), string postalCode = default(string), string state = default(string), string countryCode = default(string))
        {
            // to ensure "addressLine" is required (not null)
            if (addressLine == null)
            {
                throw new InvalidDataException("addressLine is a required property for PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner and cannot be null");
            }
            else
            {
                this.AddressLine = addressLine;
            }

            // to ensure "cityName" is required (not null)
            if (cityName == null)
            {
                throw new InvalidDataException("cityName is a required property for PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner and cannot be null");
            }
            else
            {
                this.CityName = cityName;
            }

            // to ensure "postalCode" is required (not null)
            if (postalCode == null)
            {
                throw new InvalidDataException("postalCode is a required property for PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner and cannot be null");
            }
            else
            {
                this.PostalCode = postalCode;
            }

            this.PropertyName = propertyName;
            this.State = state;
            this.CountryCode = countryCode;
        }

        /// <summary>
        /// The first line of the address for this contact
        /// </summary>
        /// <value>The first line of the address for this contact</value>
        [DataMember(Name="addressLine", EmitDefaultValue=true)]
        public string AddressLine { get; set; }

        /// <summary>
        /// The name of the property for this contact
        /// </summary>
        /// <value>The name of the property for this contact</value>
        [DataMember(Name="propertyName", EmitDefaultValue=false)]
        public string PropertyName { get; set; }

        /// <summary>
        /// The city of this contact
        /// </summary>
        /// <value>The city of this contact</value>
        [DataMember(Name="cityName", EmitDefaultValue=true)]
        public string CityName { get; set; }

        /// <summary>
        /// The postal code of this contact
        /// </summary>
        /// <value>The postal code of this contact</value>
        [DataMember(Name="postalCode", EmitDefaultValue=true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// The state/region of this contact
        /// </summary>
        /// <value>The state/region of this contact</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// The country code of this contact
        /// </summary>
        /// <value>The country code of this contact</value>
        [DataMember(Name="countryCode", EmitDefaultValue=false)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner {\n");
            sb.Append("  AddressLine: ").Append(AddressLine).Append("\n");
            sb.Append("  PropertyName: ").Append(PropertyName).Append("\n");
            sb.Append("  CityName: ").Append(CityName).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner);
        }

        /// <summary>
        /// Returns true if PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner instances are equal
        /// </summary>
        /// <param name="input">Instance of PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PropertiesPropertyIdGet200ResponsePropertyContactListInnerAddressListInner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AddressLine == input.AddressLine ||
                    (this.AddressLine != null &&
                    this.AddressLine.Equals(input.AddressLine))
                ) && 
                (
                    this.PropertyName == input.PropertyName ||
                    (this.PropertyName != null &&
                    this.PropertyName.Equals(input.PropertyName))
                ) && 
                (
                    this.CityName == input.CityName ||
                    (this.CityName != null &&
                    this.CityName.Equals(input.CityName))
                ) && 
                (
                    this.PostalCode == input.PostalCode ||
                    (this.PostalCode != null &&
                    this.PostalCode.Equals(input.PostalCode))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.CountryCode == input.CountryCode ||
                    (this.CountryCode != null &&
                    this.CountryCode.Equals(input.CountryCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AddressLine != null)
                    hashCode = hashCode * 59 + this.AddressLine.GetHashCode();
                if (this.PropertyName != null)
                    hashCode = hashCode * 59 + this.PropertyName.GetHashCode();
                if (this.CityName != null)
                    hashCode = hashCode * 59 + this.CityName.GetHashCode();
                if (this.PostalCode != null)
                    hashCode = hashCode * 59 + this.PostalCode.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.CountryCode != null)
                    hashCode = hashCode * 59 + this.CountryCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
