/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lodgea-csharp.Client.OpenAPIDateConverter;

namespace lodgea-csharp.com.lodgea.model
{
    /// <summary>
    /// V1AvailabilityGetPost200Response
    /// </summary>
    [DataContract]
    public partial class V1AvailabilityGetPost200Response :  IEquatable<V1AvailabilityGetPost200Response>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1AvailabilityGetPost200Response" /> class.
        /// </summary>
        /// <param name="ratePlanList">ratePlanList.</param>
        /// <param name="name">name.</param>
        /// <param name="mealPlanList">mealPlanList.</param>
        /// <param name="roomTypeList">roomTypeList.</param>
        public V1AvailabilityGetPost200Response(List<V1AvailabilityGetPost200ResponseRatePlanListInner> ratePlanList = default(List<V1AvailabilityGetPost200ResponseRatePlanListInner>), string name = default(string), List<V1PropertyGetPost200ResponseProductListInnerMealPlanListInner> mealPlanList = default(List<V1PropertyGetPost200ResponseProductListInnerMealPlanListInner>), List<V1AvailabilityGetPost200ResponseRoomTypeListInner> roomTypeList = default(List<V1AvailabilityGetPost200ResponseRoomTypeListInner>))
        {
            this.RatePlanList = ratePlanList;
            this.Name = name;
            this.MealPlanList = mealPlanList;
            this.RoomTypeList = roomTypeList;
        }

        /// <summary>
        /// Gets or Sets RatePlanList
        /// </summary>
        [DataMember(Name="ratePlanList", EmitDefaultValue=false)]
        public List<V1AvailabilityGetPost200ResponseRatePlanListInner> RatePlanList { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets MealPlanList
        /// </summary>
        [DataMember(Name="mealPlanList", EmitDefaultValue=false)]
        public List<V1PropertyGetPost200ResponseProductListInnerMealPlanListInner> MealPlanList { get; set; }

        /// <summary>
        /// Gets or Sets RoomTypeList
        /// </summary>
        [DataMember(Name="roomTypeList", EmitDefaultValue=false)]
        public List<V1AvailabilityGetPost200ResponseRoomTypeListInner> RoomTypeList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1AvailabilityGetPost200Response {\n");
            sb.Append("  RatePlanList: ").Append(RatePlanList).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  MealPlanList: ").Append(MealPlanList).Append("\n");
            sb.Append("  RoomTypeList: ").Append(RoomTypeList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as V1AvailabilityGetPost200Response);
        }

        /// <summary>
        /// Returns true if V1AvailabilityGetPost200Response instances are equal
        /// </summary>
        /// <param name="input">Instance of V1AvailabilityGetPost200Response to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1AvailabilityGetPost200Response input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RatePlanList == input.RatePlanList ||
                    this.RatePlanList != null &&
                    input.RatePlanList != null &&
                    this.RatePlanList.SequenceEqual(input.RatePlanList)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.MealPlanList == input.MealPlanList ||
                    this.MealPlanList != null &&
                    input.MealPlanList != null &&
                    this.MealPlanList.SequenceEqual(input.MealPlanList)
                ) && 
                (
                    this.RoomTypeList == input.RoomTypeList ||
                    this.RoomTypeList != null &&
                    input.RoomTypeList != null &&
                    this.RoomTypeList.SequenceEqual(input.RoomTypeList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RatePlanList != null)
                    hashCode = hashCode * 59 + this.RatePlanList.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.MealPlanList != null)
                    hashCode = hashCode * 59 + this.MealPlanList.GetHashCode();
                if (this.RoomTypeList != null)
                    hashCode = hashCode * 59 + this.RoomTypeList.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
