/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lodgea-csharp.Client.OpenAPIDateConverter;

namespace lodgea-csharp.com.lodgea.model
{
    /// <summary>
    /// V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy
    /// </summary>
    [DataContract]
    public partial class V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy :  IEquatable<V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy" /> class.
        /// </summary>
        /// <param name="allowed">allowed.</param>
        /// <param name="byArrangement">byArrangement.</param>
        /// <param name="freeOfCharge">freeOfCharge.</param>
        public V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy(bool allowed = default(bool), bool byArrangement = default(bool), bool freeOfCharge = default(bool))
        {
            this.Allowed = allowed;
            this.ByArrangement = byArrangement;
            this.FreeOfCharge = freeOfCharge;
        }

        /// <summary>
        /// Gets or Sets Allowed
        /// </summary>
        [DataMember(Name="allowed", EmitDefaultValue=false)]
        public bool Allowed { get; set; }

        /// <summary>
        /// Gets or Sets ByArrangement
        /// </summary>
        [DataMember(Name="byArrangement", EmitDefaultValue=false)]
        public bool ByArrangement { get; set; }

        /// <summary>
        /// Gets or Sets FreeOfCharge
        /// </summary>
        [DataMember(Name="freeOfCharge", EmitDefaultValue=false)]
        public bool FreeOfCharge { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy {\n");
            sb.Append("  Allowed: ").Append(Allowed).Append("\n");
            sb.Append("  ByArrangement: ").Append(ByArrangement).Append("\n");
            sb.Append("  FreeOfCharge: ").Append(FreeOfCharge).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy);
        }

        /// <summary>
        /// Returns true if V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy instances are equal
        /// </summary>
        /// <param name="input">Instance of V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(V1PropertyGetPost200ResponsePropertyPolicyListInnerPetsPolicy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Allowed == input.Allowed ||
                    (this.Allowed != null &&
                    this.Allowed.Equals(input.Allowed))
                ) && 
                (
                    this.ByArrangement == input.ByArrangement ||
                    (this.ByArrangement != null &&
                    this.ByArrangement.Equals(input.ByArrangement))
                ) && 
                (
                    this.FreeOfCharge == input.FreeOfCharge ||
                    (this.FreeOfCharge != null &&
                    this.FreeOfCharge.Equals(input.FreeOfCharge))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Allowed != null)
                    hashCode = hashCode * 59 + this.Allowed.GetHashCode();
                if (this.ByArrangement != null)
                    hashCode = hashCode * 59 + this.ByArrangement.GetHashCode();
                if (this.FreeOfCharge != null)
                    hashCode = hashCode * 59 + this.FreeOfCharge.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
