/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing AvailablePropertiesInner1Geo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailablePropertiesInner1GeoTests
    {
        // TODO uncomment below to declare an instance variable for AvailablePropertiesInner1Geo
        //private AvailablePropertiesInner1Geo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailablePropertiesInner1Geo
            //instance = new AvailablePropertiesInner1Geo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailablePropertiesInner1Geo
        /// </summary>
        [Test]
        public void AvailablePropertiesInner1GeoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AvailablePropertiesInner1Geo
            //Assert.IsInstanceOf(typeof(AvailablePropertiesInner1Geo), instance);
        }


        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'FormattedAddress'
        /// </summary>
        [Test]
        public void FormattedAddressTest()
        {
            // TODO unit test for the property 'FormattedAddress'
        }
        /// <summary>
        /// Test the property 'Route'
        /// </summary>
        [Test]
        public void RouteTest()
        {
            // TODO unit test for the property 'Route'
        }
        /// <summary>
        /// Test the property 'StreetNumber'
        /// </summary>
        [Test]
        public void StreetNumberTest()
        {
            // TODO unit test for the property 'StreetNumber'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Test]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Locality'
        /// </summary>
        [Test]
        public void LocalityTest()
        {
            // TODO unit test for the property 'Locality'
        }
        /// <summary>
        /// Test the property 'Sublocality'
        /// </summary>
        [Test]
        public void SublocalityTest()
        {
            // TODO unit test for the property 'Sublocality'
        }
        /// <summary>
        /// Test the property 'SublocalityLevel1'
        /// </summary>
        [Test]
        public void SublocalityLevel1Test()
        {
            // TODO unit test for the property 'SublocalityLevel1'
        }
        /// <summary>
        /// Test the property 'SublocalityLevel2'
        /// </summary>
        [Test]
        public void SublocalityLevel2Test()
        {
            // TODO unit test for the property 'SublocalityLevel2'
        }
        /// <summary>
        /// Test the property 'SublocalityLevel3'
        /// </summary>
        [Test]
        public void SublocalityLevel3Test()
        {
            // TODO unit test for the property 'SublocalityLevel3'
        }
        /// <summary>
        /// Test the property 'SublocalityLevel4'
        /// </summary>
        [Test]
        public void SublocalityLevel4Test()
        {
            // TODO unit test for the property 'SublocalityLevel4'
        }
        /// <summary>
        /// Test the property 'SublocalityLevel5'
        /// </summary>
        [Test]
        public void SublocalityLevel5Test()
        {
            // TODO unit test for the property 'SublocalityLevel5'
        }
        /// <summary>
        /// Test the property 'AdministrativeAreaLevel1'
        /// </summary>
        [Test]
        public void AdministrativeAreaLevel1Test()
        {
            // TODO unit test for the property 'AdministrativeAreaLevel1'
        }
        /// <summary>
        /// Test the property 'AdministrativeAreaLevel2'
        /// </summary>
        [Test]
        public void AdministrativeAreaLevel2Test()
        {
            // TODO unit test for the property 'AdministrativeAreaLevel2'
        }
        /// <summary>
        /// Test the property 'AdministrativeAreaLevel3'
        /// </summary>
        [Test]
        public void AdministrativeAreaLevel3Test()
        {
            // TODO unit test for the property 'AdministrativeAreaLevel3'
        }
        /// <summary>
        /// Test the property 'AdministrativeAreaLevel4'
        /// </summary>
        [Test]
        public void AdministrativeAreaLevel4Test()
        {
            // TODO unit test for the property 'AdministrativeAreaLevel4'
        }
        /// <summary>
        /// Test the property 'AdministrativeAreaLevel5'
        /// </summary>
        [Test]
        public void AdministrativeAreaLevel5Test()
        {
            // TODO unit test for the property 'AdministrativeAreaLevel5'
        }
        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Test]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Test]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'PlaceId'
        /// </summary>
        [Test]
        public void PlaceIdTest()
        {
            // TODO unit test for the property 'PlaceId'
        }

    }

}
