/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing AvailablePropertiesInner1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailablePropertiesInner1Tests
    {
        // TODO uncomment below to declare an instance variable for AvailablePropertiesInner1
        //private AvailablePropertiesInner1 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailablePropertiesInner1
            //instance = new AvailablePropertiesInner1();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailablePropertiesInner1
        /// </summary>
        [Test]
        public void AvailablePropertiesInner1InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AvailablePropertiesInner1
            //Assert.IsInstanceOf(typeof(AvailablePropertiesInner1), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Test]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'UnitSystem'
        /// </summary>
        [Test]
        public void UnitSystemTest()
        {
            // TODO unit test for the property 'UnitSystem'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'ServiceList'
        /// </summary>
        [Test]
        public void ServiceListTest()
        {
            // TODO unit test for the property 'ServiceList'
        }
        /// <summary>
        /// Test the property 'CategoryList'
        /// </summary>
        [Test]
        public void CategoryListTest()
        {
            // TODO unit test for the property 'CategoryList'
        }
        /// <summary>
        /// Test the property 'UriPath'
        /// </summary>
        [Test]
        public void UriPathTest()
        {
            // TODO unit test for the property 'UriPath'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Geo'
        /// </summary>
        [Test]
        public void GeoTest()
        {
            // TODO unit test for the property 'Geo'
        }
        /// <summary>
        /// Test the property 'MediaList'
        /// </summary>
        [Test]
        public void MediaListTest()
        {
            // TODO unit test for the property 'MediaList'
        }
        /// <summary>
        /// Test the property 'AttractionList'
        /// </summary>
        [Test]
        public void AttractionListTest()
        {
            // TODO unit test for the property 'AttractionList'
        }
        /// <summary>
        /// Test the property 'LowestPrice'
        /// </summary>
        [Test]
        public void LowestPriceTest()
        {
            // TODO unit test for the property 'LowestPrice'
        }

    }

}
