/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing AvailabilitySearchPost200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilitySearchPost200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for AvailabilitySearchPost200Response
        //private AvailabilitySearchPost200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AvailabilitySearchPost200Response
            //instance = new AvailabilitySearchPost200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AvailabilitySearchPost200Response
        /// </summary>
        [Test]
        public void AvailabilitySearchPost200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AvailabilitySearchPost200Response
            //Assert.IsInstanceOf(typeof(AvailabilitySearchPost200Response), instance);
        }


        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Test]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }
        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Test]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }

    }

}
