/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing LocationSearchPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationSearchPostRequestTests
    {
        // TODO uncomment below to declare an instance variable for LocationSearchPostRequest
        //private LocationSearchPostRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocationSearchPostRequest
            //instance = new LocationSearchPostRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocationSearchPostRequest
        /// </summary>
        [Test]
        public void LocationSearchPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LocationSearchPostRequest
            //Assert.IsInstanceOf(typeof(LocationSearchPostRequest), instance);
        }


        /// <summary>
        /// Test the property 'SearchText'
        /// </summary>
        [Test]
        public void SearchTextTest()
        {
            // TODO unit test for the property 'SearchText'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'LanguageCode'
        /// </summary>
        [Test]
        public void LanguageCodeTest()
        {
            // TODO unit test for the property 'LanguageCode'
        }

    }

}
