/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInnerTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
        //private PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
            //instance = new PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
        /// </summary>
        [Test]
        public void PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdGet200ResponsePropertyFacilityInfoGuestRoomListInnerMediaListInner), instance);
        }


        /// <summary>
        /// Test the property 'IsMainImage'
        /// </summary>
        [Test]
        public void IsMainImageTest()
        {
            // TODO unit test for the property 'IsMainImage'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Test]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }
        /// <summary>
        /// Test the property 'TagList'
        /// </summary>
        [Test]
        public void TagListTest()
        {
            // TODO unit test for the property 'TagList'
        }
        /// <summary>
        /// Test the property 'ModerationLabelList'
        /// </summary>
        [Test]
        public void ModerationLabelListTest()
        {
            // TODO unit test for the property 'ModerationLabelList'
        }
        /// <summary>
        /// Test the property 'DetectionLabelList'
        /// </summary>
        [Test]
        public void DetectionLabelListTest()
        {
            // TODO unit test for the property 'DetectionLabelList'
        }
        /// <summary>
        /// Test the property 'PropertyAmenityList'
        /// </summary>
        [Test]
        public void PropertyAmenityListTest()
        {
            // TODO unit test for the property 'PropertyAmenityList'
        }
        /// <summary>
        /// Test the property 'RoomAmenityList'
        /// </summary>
        [Test]
        public void RoomAmenityListTest()
        {
            // TODO unit test for the property 'RoomAmenityList'
        }

    }

}
