/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertyGet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertyGetTests
    {
        // TODO uncomment below to declare an instance variable for PropertyGet
        //private PropertyGet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertyGet
            //instance = new PropertyGet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertyGet
        /// </summary>
        [Test]
        public void PropertyGetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertyGet
            //Assert.IsInstanceOf(typeof(PropertyGet), instance);
        }


        /// <summary>
        /// Test the property 'PropertyId'
        /// </summary>
        [Test]
        public void PropertyIdTest()
        {
            // TODO unit test for the property 'PropertyId'
        }

    }

}
