/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdGet200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdGet200Response
        //private PropertiesPropertyIdGet200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdGet200Response
            //instance = new PropertiesPropertyIdGet200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdGet200Response
        /// </summary>
        [Test]
        public void PropertiesPropertyIdGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdGet200Response
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdGet200Response), instance);
        }


        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Test]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }
        /// <summary>
        /// Test the property 'ProductList'
        /// </summary>
        [Test]
        public void ProductListTest()
        {
            // TODO unit test for the property 'ProductList'
        }

    }

}
