/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInnerTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
        //private PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
            //instance = new PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
        /// </summary>
        [Test]
        public void PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdGet200ResponsePropertyPolicyListInnerFeePolicyListInner), instance);
        }


        /// <summary>
        /// Test the property 'TypeCode'
        /// </summary>
        [Test]
        public void TypeCodeTest()
        {
            // TODO unit test for the property 'TypeCode'
        }
        /// <summary>
        /// Test the property 'Percent'
        /// </summary>
        [Test]
        public void PercentTest()
        {
            // TODO unit test for the property 'Percent'
        }
        /// <summary>
        /// Test the property 'ChargeType'
        /// </summary>
        [Test]
        public void ChargeTypeTest()
        {
            // TODO unit test for the property 'ChargeType'
        }
        /// <summary>
        /// Test the property 'ChargeFrequencyCode'
        /// </summary>
        [Test]
        public void ChargeFrequencyCodeTest()
        {
            // TODO unit test for the property 'ChargeFrequencyCode'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'ConditionList'
        /// </summary>
        [Test]
        public void ConditionListTest()
        {
            // TODO unit test for the property 'ConditionList'
        }

    }

}
