/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInnerTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
        //private PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
            //instance = new PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
        /// </summary>
        [Test]
        public void PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdGet200ResponsePropertyServiceListInnerOperationTimeListInner), instance);
        }


        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Test]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Monday'
        /// </summary>
        [Test]
        public void MondayTest()
        {
            // TODO unit test for the property 'Monday'
        }
        /// <summary>
        /// Test the property 'Tuesday'
        /// </summary>
        [Test]
        public void TuesdayTest()
        {
            // TODO unit test for the property 'Tuesday'
        }
        /// <summary>
        /// Test the property 'Wednesday'
        /// </summary>
        [Test]
        public void WednesdayTest()
        {
            // TODO unit test for the property 'Wednesday'
        }
        /// <summary>
        /// Test the property 'Thursday'
        /// </summary>
        [Test]
        public void ThursdayTest()
        {
            // TODO unit test for the property 'Thursday'
        }
        /// <summary>
        /// Test the property 'Friday'
        /// </summary>
        [Test]
        public void FridayTest()
        {
            // TODO unit test for the property 'Friday'
        }
        /// <summary>
        /// Test the property 'Saturday'
        /// </summary>
        [Test]
        public void SaturdayTest()
        {
            // TODO unit test for the property 'Saturday'
        }
        /// <summary>
        /// Test the property 'Sunday'
        /// </summary>
        [Test]
        public void SundayTest()
        {
            // TODO unit test for the property 'Sunday'
        }

    }

}
