/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInnerTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
        //private PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
            //instance = new PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
        /// </summary>
        [Test]
        public void PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdAvailabilityGet200ResponseAvailabilityListInner), instance);
        }


        /// <summary>
        /// Test the property 'RatePlanList'
        /// </summary>
        [Test]
        public void RatePlanListTest()
        {
            // TODO unit test for the property 'RatePlanList'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MealPlanList'
        /// </summary>
        [Test]
        public void MealPlanListTest()
        {
            // TODO unit test for the property 'MealPlanList'
        }
        /// <summary>
        /// Test the property 'RoomTypeList'
        /// </summary>
        [Test]
        public void RoomTypeListTest()
        {
            // TODO unit test for the property 'RoomTypeList'
        }

    }

}
