/*
 * lodgea-csharp
 *
 * LODGEA SDK for csharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdGet200ResponsePropertyRecordCreated
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdGet200ResponsePropertyRecordCreatedTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdGet200ResponsePropertyRecordCreated
        //private PropertiesPropertyIdGet200ResponsePropertyRecordCreated instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdGet200ResponsePropertyRecordCreated
            //instance = new PropertiesPropertyIdGet200ResponsePropertyRecordCreated();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdGet200ResponsePropertyRecordCreated
        /// </summary>
        [Test]
        public void PropertiesPropertyIdGet200ResponsePropertyRecordCreatedInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdGet200ResponsePropertyRecordCreated
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdGet200ResponsePropertyRecordCreated), instance);
        }


        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Test]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Tenant'
        /// </summary>
        [Test]
        public void TenantTest()
        {
            // TODO unit test for the property 'Tenant'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Test]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

    }

}
