/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://docs.lodgea.io for more information.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing PropertiesPropertyIdGet200ResponseProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PropertiesPropertyIdGet200ResponsePropertyTests
    {
        // TODO uncomment below to declare an instance variable for PropertiesPropertyIdGet200ResponseProperty
        //private PropertiesPropertyIdGet200ResponseProperty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PropertiesPropertyIdGet200ResponseProperty
            //instance = new PropertiesPropertyIdGet200ResponseProperty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PropertiesPropertyIdGet200ResponseProperty
        /// </summary>
        [Test]
        public void PropertiesPropertyIdGet200ResponsePropertyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PropertiesPropertyIdGet200ResponseProperty
            //Assert.IsInstanceOf(typeof(PropertiesPropertyIdGet200ResponseProperty), instance);
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecordCreated'
        /// </summary>
        [Test]
        public void RecordCreatedTest()
        {
            // TODO unit test for the property 'RecordCreated'
        }
        /// <summary>
        /// Test the property 'RecordModified'
        /// </summary>
        [Test]
        public void RecordModifiedTest()
        {
            // TODO unit test for the property 'RecordModified'
        }
        /// <summary>
        /// Test the property 'PropertyInfo'
        /// </summary>
        [Test]
        public void PropertyInfoTest()
        {
            // TODO unit test for the property 'PropertyInfo'
        }
        /// <summary>
        /// Test the property 'GuestInfo'
        /// </summary>
        [Test]
        public void GuestInfoTest()
        {
            // TODO unit test for the property 'GuestInfo'
        }
        /// <summary>
        /// Test the property 'AwardList'
        /// </summary>
        [Test]
        public void AwardListTest()
        {
            // TODO unit test for the property 'AwardList'
        }
        /// <summary>
        /// Test the property 'ContactList'
        /// </summary>
        [Test]
        public void ContactListTest()
        {
            // TODO unit test for the property 'ContactList'
        }
        /// <summary>
        /// Test the property 'FacilityInfo'
        /// </summary>
        [Test]
        public void FacilityInfoTest()
        {
            // TODO unit test for the property 'FacilityInfo'
        }
        /// <summary>
        /// Test the property 'MediaList'
        /// </summary>
        [Test]
        public void MediaListTest()
        {
            // TODO unit test for the property 'MediaList'
        }
        /// <summary>
        /// Test the property 'Geo'
        /// </summary>
        [Test]
        public void GeoTest()
        {
            // TODO unit test for the property 'Geo'
        }
        /// <summary>
        /// Test the property 'Published'
        /// </summary>
        [Test]
        public void PublishedTest()
        {
            // TODO unit test for the property 'Published'
        }
        /// <summary>
        /// Test the property 'PolicyList'
        /// </summary>
        [Test]
        public void PolicyListTest()
        {
            // TODO unit test for the property 'PolicyList'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'CancellationGracePeriod'
        /// </summary>
        [Test]
        public void CancellationGracePeriodTest()
        {
            // TODO unit test for the property 'CancellationGracePeriod'
        }
        /// <summary>
        /// Test the property 'ServiceList'
        /// </summary>
        [Test]
        public void ServiceListTest()
        {
            // TODO unit test for the property 'ServiceList'
        }

    }

}
