/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistanceTests
    {
        // TODO uncomment below to declare an instance variable for V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance
        //private V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance
            //instance = new V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance
        /// </summary>
        [Test]
        public void V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance
            //Assert.IsInstanceOf(typeof(V1AvailabilitySearchPost200ResponseListInnerAttractionListInnerDistance), instance);
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

    }

}
