/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing V1LocationSearchPost200ResponseListInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LocationSearchPost200ResponseListInnerTests
    {
        // TODO uncomment below to declare an instance variable for V1LocationSearchPost200ResponseListInner
        //private V1LocationSearchPost200ResponseListInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1LocationSearchPost200ResponseListInner
            //instance = new V1LocationSearchPost200ResponseListInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1LocationSearchPost200ResponseListInner
        /// </summary>
        [Test]
        public void V1LocationSearchPost200ResponseListInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" V1LocationSearchPost200ResponseListInner
            //Assert.IsInstanceOf(typeof(V1LocationSearchPost200ResponseListInner), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'LowestPrice'
        /// </summary>
        [Test]
        public void LowestPriceTest()
        {
            // TODO unit test for the property 'LowestPrice'
        }
        /// <summary>
        /// Test the property 'PropertyId'
        /// </summary>
        [Test]
        public void PropertyIdTest()
        {
            // TODO unit test for the property 'PropertyId'
        }
        /// <summary>
        /// Test the property 'PropertyUriName'
        /// </summary>
        [Test]
        public void PropertyUriNameTest()
        {
            // TODO unit test for the property 'PropertyUriName'
        }
        /// <summary>
        /// Test the property 'PropertyUriPath'
        /// </summary>
        [Test]
        public void PropertyUriPathTest()
        {
            // TODO unit test for the property 'PropertyUriPath'
        }

    }

}
