/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceListTests
    {
        // TODO uncomment below to declare an instance variable for V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList
        //private V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList
            //instance = new V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList
        /// </summary>
        [Test]
        public void V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList
            //Assert.IsInstanceOf(typeof(V1PropertyGetPost200ResponseProductListInnerRatePlanListInnerPricingListInnerPriceList), instance);
        }


        /// <summary>
        /// Test the property '_4'
        /// </summary>
        [Test]
        public void _4Test()
        {
            // TODO unit test for the property '_4'
        }
        /// <summary>
        /// Test the property '_5'
        /// </summary>
        [Test]
        public void _5Test()
        {
            // TODO unit test for the property '_5'
        }
        /// <summary>
        /// Test the property '_6'
        /// </summary>
        [Test]
        public void _6Test()
        {
            // TODO unit test for the property '_6'
        }
        /// <summary>
        /// Test the property '_7'
        /// </summary>
        [Test]
        public void _7Test()
        {
            // TODO unit test for the property '_7'
        }
        /// <summary>
        /// Test the property '_8'
        /// </summary>
        [Test]
        public void _8Test()
        {
            // TODO unit test for the property '_8'
        }
        /// <summary>
        /// Test the property '_9'
        /// </summary>
        [Test]
        public void _9Test()
        {
            // TODO unit test for the property '_9'
        }
        /// <summary>
        /// Test the property '_10'
        /// </summary>
        [Test]
        public void _10Test()
        {
            // TODO unit test for the property '_10'
        }
        /// <summary>
        /// Test the property '_11'
        /// </summary>
        [Test]
        public void _11Test()
        {
            // TODO unit test for the property '_11'
        }
        /// <summary>
        /// Test the property '_12'
        /// </summary>
        [Test]
        public void _12Test()
        {
            // TODO unit test for the property '_12'
        }
        /// <summary>
        /// Test the property '_13'
        /// </summary>
        [Test]
        public void _13Test()
        {
            // TODO unit test for the property '_13'
        }
        /// <summary>
        /// Test the property '_14'
        /// </summary>
        [Test]
        public void _14Test()
        {
            // TODO unit test for the property '_14'
        }
        /// <summary>
        /// Test the property '_15'
        /// </summary>
        [Test]
        public void _15Test()
        {
            // TODO unit test for the property '_15'
        }
        /// <summary>
        /// Test the property '_16'
        /// </summary>
        [Test]
        public void _16Test()
        {
            // TODO unit test for the property '_16'
        }
        /// <summary>
        /// Test the property '_17'
        /// </summary>
        [Test]
        public void _17Test()
        {
            // TODO unit test for the property '_17'
        }
        /// <summary>
        /// Test the property '_18'
        /// </summary>
        [Test]
        public void _18Test()
        {
            // TODO unit test for the property '_18'
        }
        /// <summary>
        /// Test the property '_19'
        /// </summary>
        [Test]
        public void _19Test()
        {
            // TODO unit test for the property '_19'
        }
        /// <summary>
        /// Test the property '_20'
        /// </summary>
        [Test]
        public void _20Test()
        {
            // TODO unit test for the property '_20'
        }
        /// <summary>
        /// Test the property '_21'
        /// </summary>
        [Test]
        public void _21Test()
        {
            // TODO unit test for the property '_21'
        }
        /// <summary>
        /// Test the property '_22'
        /// </summary>
        [Test]
        public void _22Test()
        {
            // TODO unit test for the property '_22'
        }
        /// <summary>
        /// Test the property '_23'
        /// </summary>
        [Test]
        public void _23Test()
        {
            // TODO unit test for the property '_23'
        }

    }

}
