/*
 * lodgea-csharp
 *
 * LODGEA SDK for CSharp. Check out https://lodgea.redoc.ly for more information.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@lodgea.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lodgea-csharp.com.lodgea.controllers;
using lodgea-csharp.com.lodgea.model;
using lodgea-csharp.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lodgea-csharp.Test
{
    /// <summary>
    ///  Class for testing V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInnerTests
    {
        // TODO uncomment below to declare an instance variable for V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner
        //private V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner
            //instance = new V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner
        /// </summary>
        [Test]
        public void V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner
            //Assert.IsInstanceOf(typeof(V1PropertyGetPost200ResponsePropertyFacilityInfoGuestRoomListInner), instance);
        }


        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'RoomId'
        /// </summary>
        [Test]
        public void RoomIdTest()
        {
            // TODO unit test for the property 'RoomId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Test]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }
        /// <summary>
        /// Test the property 'DescriptionText'
        /// </summary>
        [Test]
        public void DescriptionTextTest()
        {
            // TODO unit test for the property 'DescriptionText'
        }
        /// <summary>
        /// Test the property 'ImageList'
        /// </summary>
        [Test]
        public void ImageListTest()
        {
            // TODO unit test for the property 'ImageList'
        }
        /// <summary>
        /// Test the property 'RoomTypeCode'
        /// </summary>
        [Test]
        public void RoomTypeCodeTest()
        {
            // TODO unit test for the property 'RoomTypeCode'
        }
        /// <summary>
        /// Test the property 'IsNonSmoking'
        /// </summary>
        [Test]
        public void IsNonSmokingTest()
        {
            // TODO unit test for the property 'IsNonSmoking'
        }
        /// <summary>
        /// Test the property 'RoomTypeName'
        /// </summary>
        [Test]
        public void RoomTypeNameTest()
        {
            // TODO unit test for the property 'RoomTypeName'
        }
        /// <summary>
        /// Test the property 'AmenityList'
        /// </summary>
        [Test]
        public void AmenityListTest()
        {
            // TODO unit test for the property 'AmenityList'
        }
        /// <summary>
        /// Test the property 'MaxOccupancy'
        /// </summary>
        [Test]
        public void MaxOccupancyTest()
        {
            // TODO unit test for the property 'MaxOccupancy'
        }
        /// <summary>
        /// Test the property 'MessageList'
        /// </summary>
        [Test]
        public void MessageListTest()
        {
            // TODO unit test for the property 'MessageList'
        }
        /// <summary>
        /// Test the property 'MediaList'
        /// </summary>
        [Test]
        public void MediaListTest()
        {
            // TODO unit test for the property 'MediaList'
        }
        /// <summary>
        /// Test the property 'MaxAdultOccupancy'
        /// </summary>
        [Test]
        public void MaxAdultOccupancyTest()
        {
            // TODO unit test for the property 'MaxAdultOccupancy'
        }
        /// <summary>
        /// Test the property 'MaxChildOccupancy'
        /// </summary>
        [Test]
        public void MaxChildOccupancyTest()
        {
            // TODO unit test for the property 'MaxChildOccupancy'
        }

    }

}
